import { chromium } from '@playwright/test';
import { writeFile } from 'node:fs/promises';
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://localhost:5173');await page.getByRole('button',{name:'游览潇湘馆',exact:true}).waitFor();await page.evaluate(()=>document.fonts.ready);
const before=await page.locator('canvas').screenshot();
const area=await page.locator('canvas').boundingBox();
await page.mouse.move(area.x+area.width*.65,area.y+area.height*.65);await page.mouse.down();await page.mouse.move(area.x+area.width*.35,area.y+area.height*.65,{steps:20});await page.mouse.up();
const after=await page.locator('canvas').screenshot();
const cameraChangesImage=!before.equals(after);
await page.getByRole('button',{name:'返回全园',exact:true}).click();
const timing=await page.evaluate(()=>new Promise(resolve=>{const times=[];const start=performance.now();let last=start;function frame(t){times.push(t-last);last=t;if(t-start<2000)requestAnimationFrame(frame);else resolve({frames:times.length,durationMs:Math.round(t-start),averageFps:Math.round(times.length/(t-start)*1000)});}requestAnimationFrame(frame);}));
await page.screenshot({path:'docs/preview.png',fullPage:true});
const sizes=[];
for(const [width,height] of [[1280,800],[768,1024],[390,844]]){await page.setViewportSize({width,height});await page.reload();await page.getByRole('button',{name:'游览潇湘馆',exact:true}).waitFor();sizes.push({width,height,overflow:await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth)});if(width===390)await page.screenshot({path:'docs/mobile-preview.png',fullPage:true});}
await page.emulateMedia({reducedMotion:'reduce'});await page.getByRole('button',{name:'俯视',exact:true}).click();
const reducedMotionWorks=await page.getByRole('button',{name:'俯视',exact:true}).evaluate(e=>e.classList.contains('active'));
await writeFile('docs/browser-check.json',JSON.stringify({cameraChangesImage,timing,sizes,reducedMotionWorks,errors,environment:'Local headless Chrome; RAF sampling is not a hardware performance certification'},null,2));
await browser.close();
console.log(JSON.stringify({cameraChangesImage,timing,sizes,reducedMotionWorks,errors}));
